version: "3.9"
services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./.config/nginx/:/etc/nginx/conf.d/
      - ./.config/certbot/conf:/etc/letsencrypt
      - ./.config/certbot/www:/var/www/certbot
    networks:
      app_network:
        ipv4_address: 172.20.0.4
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./.config/certbot/conf:/etc/letsencrypt
      - ./.config/certbot/www:/var/www/certbot
    networks:
      app_network:
        ipv4_address: 172.20.0.3
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  api-dev:
    container_name: ${API_NAME}-api
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    volumes:
      - ./:/app
    env_file:
      - .env
    networks:
      app_network:
        ipv4_address: 172.20.0.2
    ports:
      - "${API_PORT}:${API_PORT}"
networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1
